### ISSUE TITLE
About using the original  power board

### ISSUE THREAD

**Issue by JerryHe2084** [MouseBiteLabs/Game-Boy-Pocket-Color#2]
Hi there，first thanks for sharing the wonderful project！
I have a question about using the original power board. If I don't change my screen to IPS screen, still using the GBC original screen, can I use the original  power board? Or you still recommend using the new verson power board？
Thank you！

**Comment by MouseBiteLabs** [comment]
You can't use an original screen at all, and you can't use an OEM power
board either. You have to use an IPS kit and a new power board.
