### ISSUE TITLE
1.6 thickness

### ISSUE THREAD

**Issue by vcesne** [MouseBiteLabs/Game-Boy-Pocket-Color#3]
I ordered 1.6mm thickness PCBs without intention. Can I still continue my project or will it be really annoying?
Thank you for your amazing work.

**Comment by MouseBiteLabs** [comment]
Thanks!
The only boards that will work ok in 1.6mm are the power board and the
headphone board. The CPU and IPS boards will basically make the front and
back halves of the shell gap in the middle. Functionally it's fine, but I
don't think you'll want to have a gap between halves of the Game Boy!
