### ISSUE TITLE
Installing ips kits leads voltage problem

### ISSUE THREAD

**Issue by hualazimo7** [MouseBiteLabs/Game-Boy-Pocket-Color#6]
Assembled board can be powered on and load cartridge with sound normally.
While when I intall the IPS screen kits，the power Led turns off and the "EM6" becomes so hot.

I checked the power board, the output voltage was normal, 5V, without screen kits. Voltage on the DC even lowed to 2.4V when installed IPS kits..

Also I checked the legs of cpu which was soldered correctly...

I don't know what should I do or check..

**Comment by MouseBiteLabs** [comment]
You likely have a short somewhere, you will need to figure out where.

I cannot provide troubleshooting advice, the issues section is meant for
issues with the repository.
